language: go
go:
  - 1.11.x

env:
  global:
    - VERSION=1.65.0
    - GO111MODULE=on

before_install:
  - sudo apt-get update

script:
  - ./build.sh

deploy:
  provider: releases
  api_key:
    secure: sWHtOPjMy+fImk/dc1HjlJp5eGPiwn2eZ3lYJoTf8qM2hJ1eXOax9O0DnUxlDDMh5/uC37aSIb3HP4+MqQwn/FGrwnBgnhUBx+xtrtVXIgvKWqXw3499kTCiPnQeALK9LKNnW86PrKwi2pGCegpDvNAkBwmr1YQnszN390qJ1vawabJsR0gaVsZ4N2VbukfT4IbXgvxRuJ6bziO8yGYO/8hAvjLpVDvbEw9nLAI84k9oaJWQ9HVX0ziknu3epgobuIEkk1k/Zp+n+CoEJKAD2OlWvbhBattxvGw0NUYaiqGJ1GAhIgTf53Du6qTWWKWyZb8gLZ2hA6/rbNBuJhslgj/n7wBedoCqQEWSoVCN964Ou864MEBEJCQoXflv8X+BMl2OstCOic6ntEB/Qkc/68fjZfV4gTS7cOs1WVMfZpj0tnMgQ8C33fX0ncdqlMonEMwd9LhX8p0ztoQhmOZBLj7I/bfFr3fekU0Ax8HLeXbrzJMHNJBLs+HUh4wSAA8/E1qJo9k8eHwrKF12ZJh4lT2MveDIdUXUIpHt3BvYLdwVbE6VS/66f1GkUVd66C2oVnPnr2n1XF/J5XL/CzPmfJixqE34GYjhwCN00IbILTIC59BrytZQ/Z2SbZAiZOt2V1KTGU2L7icbbf+3pGgcgE3Q16A21bYjts/uiOMNLz4=
  file_glob: true
  file: release/*
  skip_cleanup: true
  draft: true
  on:
    tags: true

notifications:
  webhooks:
    secure: 3dU7HxlJ28+ynPZqU/fi8QpAuDXS/qW6uLozz0pUEAIkGGWFiAcutwW0fxhTJngxbrOpOQxpmM/1QGICvm6pmTwSKRvHq7M0QgkcLklM/g+r0qRCBnP9Xe9iqNdBydH7rx7eie+s9WFoOC04r6BckVB6U3eIAQZfSHg1S84/MReHgKau61ZHilkPXMRG5dvieRQ6A/uXEzsP1Bs384xZfX+GJiI5PuAfLEqgngWVl0Siq0tp32+HY4vWCVXJbekZQeNt0GWPR79fYMjXYxqoykt2hLtqI1hY9D0sB+7DVnsT+obHoKuz2xrc+LSstIqz+ScepduSKoDxxvyypMGd71T1umiMqpN8z+Uinrhk/MM4eluUm7HBodx5JzlQ41LBJmcXIAlAeVvwiekH2/0RbYRMCStYZhpmNGGd+2jJHZ5FgzH+885GJ8jOtUa7SzOOy5hfDsUONEDbtOc70+RaQJZezH/AIANmpggVHcEkugjzpDAgp6FBAu7dWuac/+7oQyBj61g7XhDKyww84nRtfTJcDSmDHBjlBdrf2Y9aCBs7p3xywksF4PxZTmx5oSDiNkr3n80/CeLTpGGlCGjIo3jDXzKNhTstTvN8CSlure+4FsAkuNv+pixDq6CZiuKicNi4dsNwykC+dqKQ+t4MXlHc10csqw96RX6Ms1kASi0=
