language: go
go: 1.9
sudo: required

before_install:
  - sudo apt-get update
  - java -version
  - ant -version
  - go version
  - go env

script:
  - ant release.xgo

after_success:
  - export APP_VERSION=`cat bin/tmp/version.dat`
  - echo $APP_VERSION
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - git tag $APP_VERSION -a -m "Generated tag from TravisCI for $APP_VERSION"
  - ls -al bin/release

deploy:
  provider: releases
  api_key:
    secure: eshUquuMnGbmuOXA6VuxugGsiXzv0eNUbkQ8Jx2/rBgHsnQ45YVlB+Zluk0tRadUqhZJEYZN9DbI9rzc/hgCkWwSQ6QkKMJrcW9GUgBw305LSPfxLvx7Krt4sdJhl7K6wrANEePxOH/fd8bFKuZNfyPvyRK7vRTaPxC0HU+4ZOGecthUHCT6E5B2OUHvL8D4zf1ljRqMs1/0COrtR6SQNLOofPxSix+S9bBfYRlh4BPQXq+rQua6/NEvmUoBE1f8e7w8r7raDoha+gST5XiH77WQFZVVQi6Y4mqEDanyWEFeAXYDCcLw3aW4I3/u40gkO9R4xlWW1cYJCoRhge+o4XcffnY6rq08c9hzPj/V3wNiKWtjC/kHwvzQubyA/wYSZZmr3UaQhHtdmkPPrDWfOAjKgRMr2muqxpP55U0dVpi6zlnfXNa4WP0m/desK8ux5fvIlzZKuIgBXzbiJ0Ns60p4BuILQU2TS8H8D/CHo3iWBTzqJO58hfswVaL5wke8xoQ+TI5TF9Se9jwREOqmFblbFZNOOuKrS/8uq/WQ7PvSiD3layFtRm4JUjZnV5Soj9+wqbPMtP6F1Iv4iQe25/eoeROiZCufgZGhD8vJ7EiiNvj740+7rj+TeiVuHwKMxeiSLCjr+N5Z2ymfG0nL3+aeDDJ9WSYBifpAWZcIJsU=
  file_glob: true
  file: bin/release/*
  skip_cleanup: true
  draft: true
  on:
    repo: crazy-max/firefox-history-merger
    tags: false

notifications:
  webhooks:
    secure: UdVyqpP9X7RR4g9A4qOuP03xG24bpmKc35zgWBfiZWUXX0uoAyPwmuU90rndAn2CClUss3TXvV5N5nPVxRb5KsB6/Lp2GGmKMoeU1RuhK9YcF8DuZp9NuPx7R7InGM/eyRFWw9RMpukksCtgY0+lOtzJBd16UlVv/FGqNenHVWosWXq07Pdxd0mXn5DKUOOCXEm17O0EMKnqruVOGRPPSVr7vbBaNaYZRN+NAJnBdM26MQmW31yXT15o7ToZDacSARIRqoyCLFLBg8vapDl9htfPYOvKbViZRBwYzV5vQRUCBI1it4TRwd+JHy3L6apzidCdzxoYjV5hjWONVJiNvIwJXDv3Ya2fP3hx4fHN+hcJsvwQcqkhvUSPJO2mSdTGDQNSXBI9YXanvO3dRper8D8z1lBUm7s2dpXTb9BBz0UeuvAc3KOuiXSxejm58Vk+KIYy9AE2rD52HDJeHPoSIuzErWcXKZq5hDNowaLD2bBCOjlMtNYclX2ET/vkL5Vg1cY/MB1Ux9G57o1w+VkCgiuSKa9Y7v7VzzVAodxTxmByXhA7R7zJ3c6x1CbzbIxgWg35431o2bVMOZd6JFtODG5RkGr47pEQEXR6bUJBzZiH49DEo9+yKKRwuOEvyHQnB3M1gfpKwA7aJ5bFC2dFmEMuYcC5CEANgIvWqb4L8/w=
