name: build

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Prepare release
        id: prepare
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo ::set-output name=tag_name::${GITHUB_REF#refs/tags/}
          else
            echo ::set-output name=tag_name::snapshot
          fi
      -
        # https://github.com/actions/checkout
        name: Checkout
        uses: actions/checkout@v1
      -
        # https://github.com/crazy-max/ghaction-xgo
        name: Xgo
        uses: crazy-max/ghaction-xgo@master
        with:
          go_version: 1.12.4
          dest: release
          prefix: firefox-history-merger
          targets: windows/386,windows/amd64,linux/386,linux/amd64,darwin/386,darwin/amd64
          ldflags: -s -w -X main.version=${{ steps.prepare.outputs.tag_name }}
      -
        name: Check
        if: success()
        run: |
          ./release/firefox-history-merger-linux-amd64 --version
      -
        # https://github.com/softprops/action-gh-release
        name: GitHub Release
        uses: softprops/action-gh-release@v1
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: release/*
          name: ${{ steps.prepare.outputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
