name: build

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Prepare release
        id: prepare
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo ::set-output name=tag_name::${GITHUB_REF#refs/tags/}
          else
            echo ::set-output name=tag_name::snapshot
          fi
      -
        name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.12.4
      -
        name: Set GOPATH
        # temporary fix (see https://github.com/actions/setup-go/issues/14)
        run: |
          echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
          echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"
      -
        # https://github.com/actions/checkout
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Xgo
        uses: crazy-max/ghaction-xgo@master
        with:
          go_version: 1.12.4
          targets: windows/386,windows/amd64,linux/386,linux/amd64,darwin/386,darwin/amd64
          out: release/firefox-history-merger
          ldflags: -s -w -X main.version=${{ steps.prepare.outputs.tag_name }}
      -
        name: Check
        if: success()
        run: |
          file release/*
          ./release/firefox-history-merger-linux-amd64 --version
      -
        name: GitHub Release
        if: success() && startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go get -u github.com/tcnksm/ghr
          ghr --version
          ghr -n ${{ steps.prepare.outputs.tag_name }} -draft ${{ steps.prepare.outputs.tag_name }} release/
